# Generated by Django 3.2.6 on 2021-08-26 04:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='accounts.customuser')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, max_length=255, null=True, upload_to=user_profile.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif']), django.core.validators.validate_image_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
