# Generated by Django 3.2.6 on 2021-08-26 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(db_index=True, max_length=255, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True, verbose_name='接続元IPアドレス')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='me')),
                ('password', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('http_accept', models.CharField(max_length=1025, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
            ],
            options={
                'db_table': 'failed_login_attempt',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ログイン時刻')),
                ('refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='リフレッシュトークン発行時刻')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='ログアウト時刻')),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True, verbose_name='接続元IPアドレス')),
                ('user_agent', models.CharField(db_index=True, max_length=255, verbose_name='User-Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'login_record',
                'ordering': ['-id'],
            },
        ),
    ]
