# Generated by Django 3.2.6 on 2021-08-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='地域コード')),
                ('name', models.CharField(max_length=255, verbose_name='地域名')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='カテゴリコード')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GovOrg',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='担当機関コード')),
                ('name', models.CharField(max_length=255, verbose_name='担当機関名')),
            ],
            options={
                'db_table': 'gov_org',
            },
        ),
        migrations.CreateModel(
            name='StatName',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='政府統計コード')),
                ('name', models.CharField(max_length=255, verbose_name='政府統計名')),
            ],
            options={
                'db_table': 'stat_name',
            },
        ),
        migrations.CreateModel(
            name='StatsCode',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='統計表ID {stat_name}_{gov_ort}_{title.zfill(3)}')),
                ('statistics_name', models.CharField(max_length=255, verbose_name='提供分類1')),
                ('table_name', models.CharField(max_length=255, verbose_name='テーブル名')),
                ('explanation', models.CharField(max_length=255, verbose_name='説明')),
                ('gov_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.govorg', verbose_name='担当機関コード')),
                ('stat_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.statname', verbose_name='政府統計コード')),
            ],
            options={
                'db_table': 'stats_code',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='年度コード')),
                ('date', models.CharField(max_length=8, verbose_name='date')),
            ],
            options={
                'db_table': 'time',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='統計コード')),
                ('name', models.CharField(max_length=255, verbose_name='統計コード名')),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='サブカテゴリコード')),
                ('name', models.CharField(max_length=255, verbose_name='サブカテゴリ名')),
                ('unit', models.CharField(max_length=255, null=True, verbose_name='表示単位')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.category', verbose_name='カテゴリ')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='StatsData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='単位コード')),
                ('value', models.CharField(max_length=255, null=True, verbose_name='統計データ数値')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.area', verbose_name='地域コード')),
                ('category', models.ManyToManyField(to='estat.Category', verbose_name='カテゴリコード')),
                ('stats_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.statscode', verbose_name='統計表 表ID')),
                ('sub_category', models.ManyToManyField(to='estat.SubCategory', verbose_name='サブカテゴリコード')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.time', verbose_name='年度コード')),
            ],
            options={
                'db_table': 'stats_data',
            },
        ),
        migrations.AddField(
            model_name='statscode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.title', verbose_name='表題コード'),
        ),
        migrations.AddField(
            model_name='category',
            name='stats_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.statscode', verbose_name='統計表 表ID'),
        ),
        migrations.AddField(
            model_name='area',
            name='stats_code',
            field=models.ManyToManyField(to='estat.StatsCode', verbose_name='統計表 表ID'),
        ),
    ]
