# Generated by Django 3.2.7 on 2021-09-17 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.area', verbose_name='地域コード')),
                ('stats_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estat.statscode', verbose_name='統計表 表ID')),
                ('sub_category', models.ManyToManyField(to='estat.SubCategory', verbose_name='サブカテゴリコード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'stat_history',
            },
        ),
    ]
