# Generated by Django 3.2.7 on 2021-10-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estat', '0002_stathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='statscode',
            name='table_name_alias',
            field=models.CharField(max_length=255, null=True, verbose_name='テーブル名の省略名称'),
        ),
    ]
