# Generated by Django 3.2.7 on 2021-10-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estat', '0003_statscode_table_name_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statscode',
            options={'ordering': ['id']},
        ),
    ]
